function getRandom(array) {
    return array.splice(Math.floor(Math.random() * array.length), 1);
}

let letters = [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'R',
    'S',
    'T',
    'W',
];

function getLetter() {
    return getRandom(letters);
}
// 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12
let categories = [
    'A boy\'s name',
    'U.S. cities',
    'Things that are cold',
    'School supplies',
    'Pro sports teams',
    'Insects',
    'Breakfast foods',
    'Furnature',
    'TV shows',
    'Things found in the ocean',
    'Presidents',
    'Product names',
    'Vegetables',
    'States',
    'Things you throw away',
    'Occupation',
    'Appliances',
    'Cartoon characters',
    'Types of drink',
    'Musical groups',
    'Store names',
    'Things at a football game',
    'Trees',
    'Personality traits',
    'Articles of clothing',
    'Desserts',
    'Car parts',
    'Things found on a map',
    'Atheletes',
    '4-letter words',
    'Items in a refridgerator',
    'Farm animals',
    'Street names',
    'Things at the beach',
    'Colors',
    'Tools',
    'Fictional characters',
    'Menu items',
    'Magazines',
    'Capitals',
    'Items you save up to buy',
    'Footwear',
    'Something you keep hidden',
    'Items in a suitcase',
    'Things with tails',
    'Sports equipment',
    'Crimes',
    'Baby foods',
    'Famous duos and trios',
    'Things found in a desk',
    'Vacation spots',
    'Diseases',
    'Words associated with money',
    'Items in a vending machine',
    'Movie titles',
    'Games',
    'Things that you wear',
    'Things at a circus',
    'Sports',
    'Song titles',
    'Parts of the body',
    'Things you shout',
    'Birds',
    'A girl\'s name',
    'Ways to get from here to there',
    'Items in a kitchen',
    'Villains/monsters',
    'Flowers',
    'Things you replace',
    'Things that are sticky',
    'Awards/ceremonies',
    'Cars',
    'Spices/herbs',
    'Bad habits',
    'Cosmetics/toiletries',
    'Celebrities',
    'Cooking utensils',
    'Reptiles/amphibians',
    'Parks',
    'Leisure activities',
    'Things you\'re allergic to',
    'Famous females',
    'Medicine/drugs',
    'Things made of metal',
    'Hobbies',
    'People in uniform',
    'Things you plug in',
    'Animals',
    'Languages',
    'Names used in the Bible',
    'Junk food',
    'Things that grow',
    'Companies',
    'Restaurants',
    'Notorious people',
    'Fruits',
    'Things in a medicine cabinet',
    'Toys',
    'Household chores',
    'Bodies of water',
    'Authors',
    'Halloween costumes',
    'Weapons',
    'Things that are round',
    'Words associated with exercise',
    'Sandwiches',
    'Items in a catalog',
    'World leaders/politicians',
    'School subjects',
    'Excuses for being late',
    'Ice cream flavors',
    'Things that jump/bounce',
    'Television stars',
    'Things in a park',
    'Foreign cities',
    'Stones/gems',
    'Musical instruments',
    'Heroes',
    'Gifts/presents',
    'Terms of endearment',
    'Things that are black',
    'Vehicles',
    'Tropical locations',
    'College majors',
    'Dairy products',
    'Things in a souvenir shop',
    'Items in your purse/waller',
    'World records',
    'Kinds of dances',
    'Things at a zoo',
    'Things smaller than your fist',
    'Things that fly',
    'Things you eat on a diet',
    'Words ending in ly',
    'Things found under the table',
    'Things in a hotel',
    'Things with claws',
    'Reasons to skip school/work',
    'Titles people have',
    'Nicknames',
    'Things in the sky',
    'Pizza toppings',
    'Fish',
    'Countries',
    'Things that have spots',
    'Historical figures',
    'Something you\re afraid of',
    'Terms of measurement',
    'Items in this room',
    'Book titles',
];

function getCategories() {
    let html = '';
    for (let i = 0; i < 12; i++) {
        html = `${html}<li>${getRandom(categories)}</li>`;
    }
    return html;
}

document.getElementById('letter').innerText = 'Letter: ' + getLetter();
document.getElementById('categories').innerHTML = getCategories();